In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import os
import numpy as np

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
day0_prices = pd.read_csv("/Users/sudhanvabharadwaj/Downloads/IMC_Prosperity4/ROUND_1/prices_round_1_day_0.csv", sep = ';')
day0_prices.head()

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,0,0,ASH_COATED_OSMIUM,NaN,NaN,NaN,NaN,NaN,NaN,10013.0,30.0,NaN,NaN,NaN,NaN,10013.0,0.0
1,0,0,INTARIAN_PEPPER_ROOT,11991.0,19.0,NaN,NaN,NaN,NaN,12006.0,10.0,12009.0,19.0,NaN,NaN,11998.5,0.0
2,0,100,INTARIAN_PEPPER_ROOT,11994.0,9.0,11991.0,23.0,NaN,NaN,12007.0,9.0,12010.0,23.0,NaN,NaN,12000.5,0.0
3,0,100,ASH_COATED_OSMIUM,9995.0,13.0,NaN,NaN,NaN,NaN,10011.0,13.0,10013.0,30.0,NaN,NaN,10003.0,0.0
4,0,200,INTARIAN_PEPPER_ROOT,11991.0,20.0,NaN,NaN,NaN,NaN,12007.0,11.0,12010.0,20.0,NaN,NaN,11999.0,0.0

In [9]:
day0_prices.shape

(20000, 17)

In [8]:
day0_prices.isna().sum()

day                    0
timestamp              0
product                0
bid_price_1          781
bid_volume_1         781
bid_price_2         7063
bid_volume_2        7063
bid_price_3        19567
bid_volume_3       19567
ask_price_1          769
ask_volume_1         769
ask_price_2         6971
ask_volume_2        6971
ask_price_3        19599
ask_volume_3       19599
mid_price              0
profit_and_loss        0
dtype: int64

In [10]:
day0_prices.drop(['bid_price_3', 'bid_volume_3', 'ask_price_3', 'ask_volume_3'], axis = 1, inplace = True)

In [11]:
day0_prices.groupby('product').agg(['mean', 'std', 'min', 'max']).T

product               ASH_COATED_OSMIUM  INTARIAN_PEPPER_ROOT
day             mean           0.000000              0.000000
                std            0.000000              0.000000
                min            0.000000              0.000000
                max            0.000000              0.000000
timestamp       mean      499950.000000         499950.000000
                std       288689.567991         288689.567991
                min            0.000000              0.000000
                max       999900.000000         999900.000000
bid_price_1     mean        9993.521599          12492.881918
                std            5.324659            288.639177
                min         9976.000000          11991.000000
                max        10014.000000          12993.000000
bid_volume_1    mean          14.156136             11.574490
                std            5.423246              4.227749
                min            2.000000              2.000000
                max           30.000000             25.000000
bid_price_2     mean        9991.267612          12494.201085
                std            5.114830            289.396641
                min         9976.000000          11991.000000
                max        10006.000000          12989.000000
bid_volume_2    mean          24.329736             19.716589
                std            4.179109              3.570262
                min            2.000000              8.000000
                max           30.000000             25.000000
ask_price_1     mean       10009.705234          12508.217983
                std            5.439325            288.273174
                min         9984.000000          12001.000000
                max        10026.000000          13010.000000
ask_volume_1    mean          14.136822             11.530353
                std            5.311142              4.206789
                min            1.000000              3.000000
                max           30.000000             25.000000
ask_price_2     mean       10012.087615          12507.736169
                std            5.096662            288.060013
                min         9994.000000          12009.000000
                max        10026.000000          13010.000000
ask_volume_2    mean          24.435168             19.731392
                std            4.104826              3.559881
                min            2.000000              8.000000
                max           30.000000             25.000000
mid_price       mean        9987.605950          12473.922650
                std          374.025689            640.834024
                min            0.000000              0.000000
                max        10023.000000          13007.000000
profit_and_loss mean           0.000000              0.000000
                std            0.000000              0.000000
                min            0.000000              0.000000
                max            0.000000              0.000000