In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import os
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [6]:
trades0 = pd.read_csv("/Users/sudhanvabharadwaj/Downloads/IMC_Prosperity4/Data/ROUND_3/prices_round_3_day_0.csv", sep = ';')
trades0.head()

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,0,0,VEV_5400,22,25,NaN,NaN,NaN,NaN,24,25,NaN,NaN,NaN,NaN,23.0,0.0
1,0,0,VEV_6500,0,16,NaN,NaN,NaN,NaN,1,16,NaN,NaN,NaN,NaN,0.5,0.0
2,0,0,VEV_5500,8,25,NaN,NaN,NaN,NaN,9,25,NaN,NaN,NaN,NaN,8.5,0.0
3,0,0,VEV_5200,100,19,NaN,NaN,NaN,NaN,103,6,104.0,13.0,NaN,NaN,101.5,0.0
4,0,0,VEV_5300,52,6,51.0,19.0,NaN,NaN,54,25,NaN,NaN,NaN,NaN,53.0,0.0

In [12]:
trades0.columns

Index(['day', 'timestamp', 'product', 'bid_price_1', 'bid_volume_1',
       'bid_price_2', 'bid_volume_2', 'bid_price_3', 'bid_volume_3',
       'ask_price_1', 'ask_volume_1', 'ask_price_2', 'ask_volume_2',
       'ask_price_3', 'ask_volume_3', 'mid_price', 'profit_and_loss'],
      dtype='object')

In [7]:
trades0['product'].unique()

array(['VEV_5400', 'VEV_6500', 'VEV_5500', 'VEV_5200', 'VEV_5300',
       'VELVETFRUIT_EXTRACT', 'VEV_4500', 'HYDROGEL_PACK', 'VEV_5000',
       'VEV_4000', 'VEV_5100', 'VEV_6000'], dtype=object)

In [8]:
vfe0 = trades0[trades0['product']=='VELVETFRUIT_EXTRACT']
vfe0.head()

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
5,0,0,VELVETFRUIT_EXTRACT,5247,67,NaN,NaN,NaN,NaN,5253,67,NaN,NaN,NaN,NaN,5250.0,0.0
13,0,100,VELVETFRUIT_EXTRACT,5248,69,NaN,NaN,NaN,NaN,5253,23,5254.0,46.0,NaN,NaN,5250.5,0.0
25,0,200,VELVETFRUIT_EXTRACT,5248,20,5247.0,40.0,NaN,NaN,5253,60,NaN,NaN,NaN,NaN,5250.5,0.0
47,0,300,VELVETFRUIT_EXTRACT,5248,24,5247.0,40.0,NaN,NaN,5253,64,NaN,NaN,NaN,NaN,5250.5,0.0
55,0,400,VELVETFRUIT_EXTRACT,5248,25,5247.0,37.0,NaN,NaN,5253,62,NaN,NaN,NaN,NaN,5250.5,0.0

In [10]:
vfe0.isna().sum()

day                   0
timestamp             0
product               0
bid_price_1           0
bid_volume_1          0
bid_price_2        4593
bid_volume_2       4593
bid_price_3        9792
bid_volume_3       9792
ask_price_1           0
ask_volume_1          0
ask_price_2        4561
ask_volume_2       4561
ask_price_3        9823
ask_volume_3       9823
mid_price             0
profit_and_loss       0
dtype: int64

In [11]:
vfe0['mid_price_1'] = (vfe0['bid_price_1'] + vfe0['ask_price_1'])/2
vfe0['mid_price_1'].describe()

count    10000.000000
mean      5246.510250
std         13.677795
min       5216.500000
25%       5236.500000
50%       5244.500000
75%       5255.500000
max       5284.500000
Name: mid_price_1, dtype: float64